

cmd1:
	@echo "Compile Underwater_Methods_AdjointODE.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_AdjointODE.o -c ./ocp-src/Underwater_Methods_AdjointODE.cc


cmd2:
	@echo "Compile Underwater_Methods_UserFunctions.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_UserFunctions.o -c ./ocp-src/Underwater_Methods_UserFunctions.cc


cmd3:
	@echo "Compile Underwater_Methods_controls.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_controls.o -c ./ocp-src/Underwater_Methods_controls.cc


cmd4:
	@echo "Compile Underwater_Methods_problem.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_problem.o -c ./ocp-src/Underwater_Methods_problem.cc


cmd5:
	@echo "Compile Underwater.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater.o -c ./ocp-src/Underwater.cc


cmd6:
	@echo "Compile Underwater_dll_ruby.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_dll_ruby.o -c ./ocp-src/Underwater_dll_ruby.cc


cmd7:
	@echo "Compile Underwater_dll_pins.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_dll_pins.o -c ./ocp-src/Underwater_dll_pins.cc


cmd8:
	@echo "Compile Underwater_Methods_Guess.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_Guess.o -c ./ocp-src/Underwater_Methods_Guess.cc


cmd9:
	@echo "Compile Underwater_Methods_boundary_conditions.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_boundary_conditions.o -c ./ocp-src/Underwater_Methods_boundary_conditions.cc


cmd10:
	@echo "Compile Underwater_Methods_ODE.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_ODE.o -c ./ocp-src/Underwater_Methods_ODE.cc


cmd11:
	@echo "Compile Underwater_Methods_Direct.cc"
	clang++ -fPIC -Os -g -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I/usr/local/include  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/Underwater_Methods_Direct.o -c ./ocp-src/Underwater_Methods_Direct.cc
all:  cmd1 cmd2 cmd3 cmd4 cmd5 cmd6 cmd7 cmd8 cmd9 cmd10 cmd11

