

cmd1:
	@echo "Compile AliChan_Methods_controls.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_controls.o -c ./ocp-src/AliChan_Methods_controls.cc


cmd2:
	@echo "Compile AliChan_Methods_problem.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_problem.o -c ./ocp-src/AliChan_Methods_problem.cc


cmd3:
	@echo "Compile AliChan.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan.o -c ./ocp-src/AliChan.cc


cmd4:
	@echo "Compile AliChan_Methods_UserFunctions.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_UserFunctions.o -c ./ocp-src/AliChan_Methods_UserFunctions.cc


cmd5:
	@echo "Compile AliChan_dll_pins.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_dll_pins.o -c ./ocp-src/AliChan_dll_pins.cc


cmd6:
	@echo "Compile AliChan_Methods_boundary_conditions.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_boundary_conditions.o -c ./ocp-src/AliChan_Methods_boundary_conditions.cc


cmd7:
	@echo "Compile AliChan_dll_ruby.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_dll_ruby.o -c ./ocp-src/AliChan_dll_ruby.cc


cmd8:
	@echo "Compile AliChan_Methods_Guess.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_Guess.o -c ./ocp-src/AliChan_Methods_Guess.cc


cmd9:
	@echo "Compile AliChan_Methods_AdjointODE.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_AdjointODE.o -c ./ocp-src/AliChan_Methods_AdjointODE.cc


cmd10:
	@echo "Compile AliChan_Methods_ODE.cc"
	clang++ -fPIC -Os -g -finline-functions -finline-hint-functions -funroll-loops -fcolor-diagnostics -std=c++11 -stdlib=libc++  -I././ocp-src -F/Library/Frameworks  -o ./ocp-src/AliChan_Methods_ODE.o -c ./ocp-src/AliChan_Methods_ODE.cc
all:  cmd1 cmd2 cmd3 cmd4 cmd5 cmd6 cmd7 cmd8 cmd9 cmd10

